Resources:
## VPC
  firstVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      ## Private Subnet
  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: us-east-1a
      VpcId: !Ref firstVPC
      CidrBlock: 10.0.0.0/24
      ## Public Subnet
  PublicSubnet2: 
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: us-east-1b
      VpcId: !Ref firstVPC
      CidrBlock: 10.0.1.0/24
       
       

   
       
    

       
        
    
  
