Resources:
## VPC
  firstVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      ## Rrivate Subnet
  subnetName:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: us-east-1a
      VpcId: !Ref firstVPC
      CidrBlock: 10.0.0.0/24
     

   
       
    

       
        
    
  
